// <auto-generated />
namespace IntroducaoAoMigrations.BancoDeDados.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Paises : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201202150944400_Paises"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so7NlW1ez9TSrjqsvios6awmjZswvVh+lx2WREVKv8/L8PTHceQgMP7J9U++nhGV7/eZ6lTMGn330MisavwW1+b3y6+AD+uhlXa3yur1+lZ/re2ezj9K74Xt3uy/a17x30DUP+d7eR+mLdVlmk5I+OM/KJv8oXX366HVb1fnn+TInOuSzl1nb5vUS7+aMupLg0erT21Hh4d2dPVDhbrZcVi2Ttod4B80X1SI3iL5ua+Kbj9Jnxbt89jxfXrRzi+wX2TvzCf36UfrVsiA2o5faep1HBre519fFRZn9bHf7+K5jgD5bENO2WUGUV5Twd/6urZ7m+H6WzfIuq8h7r/PW4yZqlLpehHHHzGZRVGynTkTuiowYWbo7IEyPv8hWKyKTJ1z6SfpaJOtk+/X7i8xCYNydBoPtksj2ROyaXeSdb0G7Wf6sqJv2adZmkwwTcTJbRJrdmsSmx4DSXUF1hDfN8buK3yY9M+4rAgaoYJ7RIBckgTxeHS3hFNMf+uLraVZmdUQDnFTlerEc0iKb3hbB9N+XT24PQYXMB6Ef9WE8vtsZe5fWnixpy44+7E7dJu7vNrG9WynocPtj5byb7UuPFaXJRykR57KYgQ1fXzdtvhijwfj1LypPyoLG6xp8kS2L87xp31Rvc9hKkpSvb5esRm6aWfn/RuNUYOg3mqH3VO++UVleZvV0ntVbi+zdnfeGFBiK9wH1vsq/q8BuVv2Dil847rOPZhNyaN4IhsZWfE2j0Gf/x3d9J+zx07wpLhwIuGTLfAqd54CaNmfL88qQmYbkY2SadGbhi7zNZkSZ47otzrNpS19P86Zhq/2TWbmmJqeLST47W365blfr9rhp8sWkvPbH+/ju5v7Z8oU4P/5yxVr7mxgCoUkWp82/XD5ZF+XM4v0swjoDIMAkKiSEFXktBO7i2kJ6US1vCUjJ9zRf5UuI2Jt8sSoJWPPl8nV2mQ/jdjMNQ4o9flpkZPoWPgXlEyNeGfXsdUEd+G+4/uhPYleKAI7+nwAAAP//BWZgq3YMAAA="; }
        }
    }
}
