// <auto-generated />
namespace IntroducaoAoMigrations.BancoDeDados.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Estados : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201202151456262_Estados"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so7NlW1ez9TSrjqsvios6awmjZswvVh+lx2WREVKv8/L8PTHceQgMP7J9U++nhGV7/eZ6lTMGn330MisavwW1+b3y6+AD+uhlXa3yur1+lZ/re2ezj9K74Xt3uy/a17x30DUP+d7eR+mLdVlmk5I+OM/KJv8oXX366HVb1fnn+TInOuSzl1nb5vUS7+aMupLg0erT21Hh4d2dPVDhbrZcVi2Ttod4B80X1SI3iL5ua+Kbj9Jnxbt89jxfXrRzi+wX2TvzCf36UfrVsiA2o5faep1HBre519fFRZn9ELp9kV0WF0yHDgKnTUs0az5KX+WlsOC8WAnfjeW735+ZJX1WV4tXVWlf4Y9//zdZfZG3NICq/93ral1PO6g8vut4cSOHCqAf8WiAJsh6M6o/4vMInwsTfz0mN4wcY3IjALdh8uOmqaYFIxBwuXQeDuR0OUs3YCJ0dPgT4dZlW6zKYkodf/bRt3qUiQO08usACiVCcLshdgTuy+XTvMzbPD2eYjyffXSSNdNs1p8RosUs/IRENa8hM1lJBrNp66xYtn25LpbTYpWVw0h3XrmlMgBKFnj3m6f5Kl9Cnodpf5tejZz2e7YddIh0E00e3/WYp6846Z2W3shrRQB/5+/a6mmO72c0L33+wnuv89ZDmRqljnMDdugxU/i2tSK91w17dgB4o+lCUVH0WkQktUvYzeJi0fUw7c3NZgHxQBhSdRk9HFNEH9hZst89viuOoX7w+O6AB/n4i2y1Ip3peZT6Sfpa3MmT7dfv7ycuBMbdaUDQLk/Znsj+ZRd551sw2yx/VtRN+zRrs0kGrXwyW0Sa3ZonTY8Ba/bny7CaaY7fVew3OdfjGAc5ij6jQS6gAtjed+a9/1oK5z4rszriUpxU5XqxHNZEw2+Llfbfl09uD0Etrg9CP+rDeHy3M/ae3uoRu6fkw6m71cQaWfzmZjbmNTLIm+Z26MWfndk19sGHMGQzhqH8/4hHehqy28T2bjVlRyM+Vu0UqE0edzfw7qkrafJRSsS5LGZQVa+vmzZfjNFg/PoXlSdlQeN1Db7IlsV53rRvqrc5kgikTb9+wG7DgKaZlf9vjNoLDP3G2Oc94wE/ClleZvV0ntVbi+zdnfeGFEQW7wPq//Wh6M8K4cMQkrt4Twj/L566rxdgib/5w4yAuq7m1wrovlYYNeD63IZ1MZL3DJxu1dP/C4Klrv/ana1+qDQYKIkx+eyj2QSzKhw8EDB04ZqJ70E2X8RgD8QzP4sBlj985xffHE9FwrBvKIbqxFB9T4BYZr20iXpi1qa4cGEY0vbLfBowi21ztjyvDM92ojrTpKPVvshpaMRJx3VbnGfTlr6e5k3DGa+fzMo1CLKY5LOz5ZfrdrVuaR7yxaS89okB3t/UPweKIc6Pv1yxK/xNDIHQpACtzb9cPlkX5czi/SyiigdAQKjUbIEFW5ivi2sL6UW1vCUgJd9Towve5IsVJfHy5svl6+wyH8btZhqGFHv8tMgonlj4FJRPjLnKqGevC+rAf8P1R3+S0qdVoqP/JwAA///Oi01JmhoAAA=="; }
        }
    }
}
